### ISSUE TITLE
Please update dependencies to json 2+ to add support for ruby 2.7+

### ISSUE THREAD

**Issue by edgartheunready** [zendesk/sunshine-conversations-ruby#19]
This project currently depends on a version of the JSON gem that was release in 2017
https://github.com/flori/json/releases/tag/v1.8.6
Please update the json dependency to json 2+
Current version is 2.3.1
https://github.com/flori/json/releases/tag/v2.3.1
Running ruby 2.7.1 and json 1.8.x results in the following warnings:
.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated

**Comment by ogabriel** [comment]
Fixed on 5.29.1
https://github.com/zendesk/sunshine-conversations-ruby/commit/d985f8813dcb983e2a36440631652460aa9d50fe#diff-667dc8066df8fc51a6affe2f5c9853cdc238c8b2150fbdf6f679b037bebc69cdL31
