### ISSUE TITLE
does the client support payment over messaging?

### ISSUE THREAD

**Issue by angelacode** [zendesk/sunshine-conversations-ruby#4]
I looks like from the documentation that smooch supports payments via stripe?  Which part of the documentation for the ruby client describes this?

I am having difficulty finding that, thanks@!

**Comment by mspensieri** [comment]
Once you have enabled Stripe on your app from the Smooch marketplace, you can use the use the [`post_message`](https://github.com/smooch/smooch-ruby/blob/master/docs/ConversationApi.md#post_message) method to send a message with an [action](https://github.com/smooch/smooch-ruby/blob/master/docs/Action.md) of type `buy`.

More information about buy actions: https://docs.smooch.io/rest/#buy

**Comment by angelacode** [comment]
I can use the "markdown" to create the payment button as well?

https://docs.smooch.io/guide/sending-images-and-buttons-shorthand/

**Comment by mspensieri** [comment]
Yes if you include the payment button syntax in your message text it will be parsed into a buy action

**Comment by angelacode** [comment]
Hi, so it looks like it takes it to a smooch.io page....is there a way to use a custom domain for that (I can create a redirect page rule in Cloudflare if I can change the base URL)...I don't think customers would continue if they go from my app to being asked permission to go to a smooch.io URL....

The altnerative looks like creating  my own button to my own stripe page...?

**Comment by mspensieri** [comment]
> if they go from my app to being asked permission to go to a smooch.io URL

Can you elaborate on what kind of "app" you're talking about? Our native SDKs (iOS, Android, and Web) all have built-in support for payment buttons, it shouldn't take you to any external URL. Here's what it looks like on iOS, taken from https://docs.smooch.io/guide/stripe-payments/:

![](https://docs.smooch.io/images/card_capture_ui.png)

For other integrations, it would indeed take you to a smooch.io URL though, we don't have an option to customize the location of that page. The alternative would be to not use our Stripe integration, and instead send a `link` action with a URL to whatever payment page you choose

**Comment by angelacode** [comment]
This is all within Messenger going to a hosted Stripe checkout.....looks like I would need to use the "link" action
